name: Build WPF

on: [push]

jobs:
  BuildDebug:

    runs-on: [self-hosted, VSPreview]

    steps:
    - uses: actions/checkout@v1
    # - name: Install Nuget
    #   uses: nuget/setup-nuget@v1
    #   with:
    #     nuget-version: '5.x'
    - name: Build
      run: .\build.cmd -pack -ci -configuration Debug -prepareMachine /p:Platform=x86
    - name: Push
      uses: actions/upload-artifact@v1
      with:
        name: WPF_Debug
        path: ./artifacts/packages/Debug/NonShipping

  BuildRelease:

    runs-on: [self-hosted, VSPreview]

    steps:
    - uses: actions/checkout@v1
    # - name: Install Nuget
    #   uses: nuget/setup-nuget@v1
    #   with:
    #     nuget-version: '5.x'
    - name: Build
      run: .\build.cmd -pack -ci -configuration Release -prepareMachine /p:Platform=x86
    - name: Push
      uses: actions/upload-artifact@v1
      with:
        name: WPF_Release
        path: ./artifacts/packages/Release/NonShipping